# Generated by Django 4.2.17 on 2025-09-23 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('daily', models.IntegerField(blank=True, null=True)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entertainment_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shopping_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bills_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('others_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
