# Generated by Django 4.2.17 on 2025-09-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='daily',
            new_name='day',
        ),
    ]
