# Generated by Django 5.2.7 on 2025-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
