# Generated by Django 5.2.7 on 2025-10-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
